pipeline { 
    agent { node { label 'master' } }
      stages {
	stage ('Install VirtualBox to Ubuntu') {
                steps {
                  sh "sudo apt-get update -y && sudo apt-get install -y vitrualbox virtualbox-ext-pack"
                      }
                }
        stage ('Curl from remote repo to local minikube') {
                steps {
                  sh '''
                       curl -Lo  minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
                        && chmod +x minikube
                     '''
                      }
                }
        stage ('Copy daemon minikube to /usr/local/bin') {
                steps {
                  sh "sudo cp minikube /usr/local/bin/ && rm minikube"
                        }
                }
        stage ('Run minikube with dashboard') {
                steps {
                  sh "minikube start && minikube dashboard"
		      }
		}
	}
}	
