pipeline { 
    agent { node { label 'ubuntu-aws' } }
      stages {
	stage ('Curl from remote repo to local minikube') {
		steps {
		  sh '''
 			curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
 			&& chmod +x minikube
		     '''
		      }
		}	
	stage ('Copy daemon minikube to /usr/local/bin') {
		steps {
	          sh "sudo cp minikube /usr/local/bin/ && rm minikube"
			}
		}
	stage ('Run minikube with dashboard') {
		steps {
		  sh "minikube start && minikube dashboard"
		      }
		}
	}
}	
